name: ToastFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0
description: Plugin for ToastFreedom
softdepend: [BukkitTelnet, TF-WorldEdit, TF-Essentials]
authors: [Madgeek1450, Prozza, PacksGaming4K]