name: ToastFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.3
description: Plugin for ToastFreedom
softdepend: [BukkitTelnet, TF-WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, PacksGamingHD]
